### ISSUE TITLE
Bug: Notification

### ISSUE THREAD

**Issue by utetrapp** [geli-lms/geli#1082]
# Bug
As a student I want to click a notification and jump straight to the changed/new unit. This works fine, when I'm on the dashboard, already in the course it fails.

**Comment by Gargamil** [comment]
Furthermore: Notification popup scrolls down when scrolling on page. 

<img width="377" alt="bildschirmfoto 2018-12-20 um 11 30 57" src="https://user-images.githubusercontent.com/5781450/50279731-df2efb80-044a-11e9-964d-335c954b2b0d.png">

**Comment by Gargamil** [comment]
Scroll bug is a bug from angular material (https://github.com/angular/material2/issues/11365)

**Comment by kesselb** [comment]
1. Visit course "A" as student
2. Edit course "B" as teacher or admin 
3. Reload current page (course "A") as student and see notification for course "B"
4. Click on notification for course "B".
5. There is no redirect to course "A".
6. After a page reload i see course "B".


![Peek 2019-03-25 22-15](https://user-images.githubusercontent.com/3902676/54954831-e5ea7480-4f4b-11e9-88cc-691a172ef040.gif)
