### ISSUE TITLE
Jump To Top Button

### ISSUE THREAD

**Issue by dboschm** [geli-lms/geli#1086]
# User Story

### As a: 
Student 

### I want:
a "jump to top" button in the course view

### so that:
I can get to the top of the course quickly.

## Acceptance criteria:
- [ ] Jump to top button at the end of course view

## Additional info:
Tracked by #793

**Comment by Gargamil** [comment]
Whether like this? (Pink small button, on top of chat button)

![image](https://user-images.githubusercontent.com/5781450/51285006-d4d23400-19ed-11e9-9768-aa85296f9f52.png)

**Comment by Gargamil** [comment]
Can be closed with #1115
