### ISSUE TITLE
🐛 BUG: AJAX behind BASIC_AUTH does not work

### ISSUE THREAD

**Issue by aeimer** [geli-lms/geli#202]
# User Story

### As a: 
Developer

### I want:
to use the software behind "basic auth"

### so that:
I can setup an secured staging system.

## Acceptance criteria:
- BasicAuth can be activated for the whole domain and everything works
  - [ ] normal html/css calls work
  - [ ] AJAX/Angular calls work

## Additional info:
I've tried to setup our staging system with basic_auth, I then realized that AJAX calls didn't work. I then excluded the /api path from basic.

**Comment by PatrickSkowronek** [comment]
@aeimer please add a testcase. I can't recreate this issue.

**Comment by aeimer** [comment]
You need to activate the HTTP BASIC Auth for the Backend:

```diff
location /api {
  proxy_pass   http://staging;
  include      conf.d/includes/proxypass.conf;
+
+ include      conf.d/includes/basic-auth.conf;
}

location / {
  proxy_pass   http://staging;
  include      conf.d/includes/proxypass.conf;

  include      conf.d/includes/basic-auth.conf;
}
```

Then run ` dc exec reverse-proxy service nginx reload` to reload the nginx config.

After these steps, the FE can't retrieve any information from the API.

**Comment by PatrickSkowronek** [comment]
Thank you @aeimer , I will look into this with the new Infrastructure team.

**Comment by danielkesselberg** [comment]
I did some research about this issue. When web frontend and api running behind basic auth its required to include the Authorization-Header (something like Basic aW52YWxpZHVzZXI6d3JvbmdwYXNzd29yZA==).  If you need to pass this header for subsequent request then you use the withCredentials flag

**Comment by aeimer** [comment]
@danielkesselberg is this issue solved?

**Comment by danielkesselberg** [comment]
No. We discusses this issue and decided that the current solution is sufficient. A solution for this issue would require that angular add the basic authentication to every request (like we do with the jwt token).
