### ISSUE TITLE
Setup a BACKUP

### ISSUE THREAD

**Issue by aeimer** [geli-lms/geli#215]
# User Story

### As a: 
Hoster

### I want:
to have a backup of ALL data

### so that:
we can restore the system if anything goes wrong.

## Acceptance criteria:
- [ ] a total serves crash is no problem
- [x] before a new version gets applied, a backup is done
- [ ] the backup is stored outside of the live server
- [x] an automatic backup is done every 24h
- [ ] a wiki/readme article about backuping is written

## Additional info:
To be discussed:
- what data we need to backup
- how do we backup them
- where do we store the backups
- how long do we store the backups?

**Comment by d89** [comment]
Recently, I was thinking about AWS. In the near future, we need lots of storage for all the videos anyways (where S3 is a super cheap and fast option). On top, AWS solves all the backup issues inherently by providing a full snapshot capability. I would like to discuss that with @utetrapp in the upcoming meetup if the university might already have an AWS account or if it would be feasable for us to create one and let the university pay :).

**Comment by aeimer** [comment]
@PatrickSkowronek please setup a backuphook on live-deploy.
Use the following folder structure:
```
geli
  |- live
    |- backups
      |- dumps_db
        |- 20171026-132456.zip (daily backup)
        |- 20171025-123424_delpoy.zip (pre deploy hook backup)
      |- monday (repeat that for each day of week)
        |- db (symlink to ../dumps_db/20171026-132456.zip)
      |- deploy
        |- db (symlink to ../dumps/20171025-123424_delpoy.zip)
```
You can ignore the daily backup folder, @micpah will do that.
Please DO NOT remove the unsymlinked deploy backups. The latest deploy-zip is symlinked to `deploy/db`.

**Comment by khase** [comment]
I added a simple backup mechanism which creates a simple Backup of the live System before updating it.
(Only includes the Database til now)

**Comment by PatrickSkowronek** [comment]
I modify the backup mechanism which now zip everything

**Comment by micpah** [comment]
Set up a daily backup for the live env which includes only the db for now (i.e. no backup of uploads yet). You guys can check it out.

**Comment by aeimer** [comment]
@khase and I tested the daily backup mechanism, works.

@micpah

**Comment by aeimer** [comment]
@d89 for this ticket is completed. We currently don't have "real" backups, only local the database on the server. We may consider to backup all data (db and uploads) or use s3 etc

**Comment by d89** [comment]
As this is a technical story, I will set it to "succesfully reviewed" even if I actually didn't review it. Currently, the AWS / S3 issue is still under investigation. We might want to talk about how the backup was actually implemented in person on thursday.

**Comment by PatrickSkowronek** [comment]
After the current events we should think about a backup. The database creates a daily backup. The files are not. S3 was an option maybe something different.

**Comment by lukas-schardt** [comment]
The wiki/readme article about backuping will be written in #838
