### ISSUE TITLE
🐛 BUG: Markdown Fullscreenmode after close does not update text properly

### ISSUE THREAD

**Issue by aeimer** [geli-lms/geli#301]
When I edit a FreeTextUnit and I change to the preview-tab, then I edit the markdown and close the popup with the `X` in the top right. The `preview` does not changes. If I go to the `edit`-Tab, the markdown is also not set. I have to click inside the editor to update the content to the current state.

All this is just a "View"-problem, the edited text/markdow is not lost

Bugissue of #247

**Comment by HPunktOchs** [comment]
Tested in Firefox 59.0, after a short Period of time (~1sec), the Markdown text gets updated.

**Comment by aeimer** [comment]
On FF59 I'm able to get the error...

**Comment by lukas-schardt** [comment]
Works in newest FF(62)
