### ISSUE TITLE
Redirect to initial URL after login

### ISSUE THREAD

**Issue by aeimer** [geli-lms/geli#318]
# User Story

### As a: 
User

### I want:
get redirected to the initially called URL after my login

### so that:
I don't have to reclick the link to get to the desired page.

## Acceptance criteria:
- [ ] when I'm not logged in and I call any by login protected page, I want to see the initial called page after I successfully logged in

## Estimate:
4h

**Comment by khase** [comment]
related, conflicting #171

**Comment by aeimer** [comment]
@khase yes this is realted and it should be implemented together with #171 . But I don't see any conflict there!
