### ISSUE TITLE
🐛 BUG: Sometimes the files for a fileunit are not available

### ISSUE THREAD

**Issue by aeimer** [geli-lms/geli#515]
# BUG
If a new course is created, I switch to the "Content"-Tab and want to add a file-unit it says "No Files available". That's ok.

Then I go to the "Media"-Tab, upload at least one file and got back to the "Content"-Tab, I sometimes get the same error as before, which now isn't correct.
Normally I should get offered the files I uploaded. After a reload of the page, the files can be added to a file-unit.

It seems like the `media`-property of the course sometimes isn't updated.

## Estimate:
4h

**Comment by lukas-schardt** [comment]
Cannot reprodcue the bug. Seems to be fixed.
