### ISSUE TITLE
Update looking of Whitelist CSV Upload 

### ISSUE THREAD

**Issue by OliverNeff** [geli-lms/geli#516]
# User Story

### As a: 
Teacher

### I want:
Upload a CSV file from obs. 

### so that:
Users are whitelistet

## Acceptance criteria:
- [ ] It should look like the other uploader
- [ ] It should have an Confirm Exit modal where you can abort the upload

## Additional info:
It is implement yet but it is outdated after last release and should be look nicer.

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by lukas-schardt** [comment]
See: #727
