### ISSUE TITLE
add french translation

### ISSUE THREAD

**Issue by armel22** [geli-lms/geli#542]
# User Story

### As a: 

User

### I want:

to have a french translation as well

### so that:

I can use the application  in my native language

## Acceptance criteria:
- [ ] translate all texts to french

## Estimated:
- 3 x 4hr

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
This is blocked by #549

**Comment by dboschm** [comment]
unfortunately there no french speaking people in the team anymore
