### ISSUE TITLE
add turkish translation

### ISSUE THREAD

**Issue by AlperUygun** [geli-lms/geli#578]
# User Story

### As a: 
User

### I want:
to have a turkish translation for turkish native speakers

### so that:
thethe application can be used in the turkish language

## Acceptance criteria:
- [ ] tranlate all texts to turkissh

## Estimated:
- 3 x 4hr
------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
This is blocked by #549

**Comment by PatrickSkowronek** [comment]
@aeimer i hoped that my "blocked comment" was enough to understand that.
