### ISSUE TITLE
Add assignments to geli

### ISSUE THREAD

**Issue by PatrickSkowronek** [geli-lms/geli#600]
# User Story

### As a: 
Student/Teacher

### I want:
a possible infrastructure for uploading assignments.

## Acceptance criteria:
- [ ] Any group can see there assignment, unlike moodle only one person can see the uploaded file
- [x] Assignments have a duty date, this date should be changeable 
- [x] For Labs there should be a duplicate function
- [x] The teacher can grade the assignment(ok/not ok) and can request changes
- [ ] Assignments can be multiple files, so that the student can swap file easily instead of packing a zip file every time

## Estimated:
- 8 x 4hr
------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by aeimer** [comment]
Check how the laws are, that may be the biggest problem...

**Comment by HPunktOchs** [comment]
related #705
