### ISSUE TITLE
🐛 BUG: Fix long build times ends travis builds

### ISSUE THREAD

**Issue by PatrickSkowronek** [geli-lms/geli#658]
At the moment we have a hotfix for travis. But if there is an error in the production build travis say it completed it. We need to fix that.

**Comment by danielkesselberg** [comment]
> At the moment we have a hotfix for travis.

@PatrickSkowronek could you please describe what "hotfix for travis" means?

**Comment by PatrickSkowronek** [comment]
This is kinda fixed. After the update to angular6 the build time for the source-maps was more than 15 mins. When a there is no output in Travis after 12 mins, Travis will fail. To optimize this we should keep angular up to date.
