### ISSUE TITLE
🐛 BUG: System type information message isn't correctly centered

### ISSUE THREAD

**Issue by grosspersky** [geli-lms/geli#736]
The system type information message (e.g. _STAGING-SYSTEM_, _DEMO - All data will be reset at 2am CEST_) isn't correctly centered compared to the rest of the frontpage layout.

See the screenshot for visual reference:
![grafik](https://user-images.githubusercontent.com/11839276/39924238-4cf90e2c-5527-11e8-8b57-be6fb8d55960.png)

**Comment by dboschm** [comment]
In the production version there is no system type information message.
