### ISSUE TITLE
Document credentials for the demo system

### ISSUE THREAD

**Issue by grosspersky** [geli-lms/geli#827]
# User Story

### As a: 

someone who evaluates geli

### I want:

to find the credentials for using the demo system easy

### so that:

i can starting testing the demo with all available roles without a problem

## Acceptance criteria:
- [ ] credentials for all roles are easy to find when trying the demo

## Additional info:
Maybe we could use the start page message to link to a page with the available credentials.

At the moment the only place where they can be found is here:
https://github.com/utetrapp/geli/issues/199#issuecomment-337379947

**Comment by kesselb** [comment]
![Screenshot from 2019-03-26 10-58-35](https://user-images.githubusercontent.com/3902676/54988172-2979c880-4fb6-11e9-8d3e-a497662d462e.png)

The position of the information box could be improved :roll_eyes:

**Comment by zHaytam** [comment]
None of those accounts work, is that normal?
