### ISSUE TITLE
Bug: Download single PDF

### ISSUE THREAD

**Issue by utetrapp** [geli-lms/geli#833]
# Staging system, course MPSE Vorstellung, Download
![grafik](https://user-images.githubusercontent.com/9103874/46191990-d8846280-c2f9-11e8-9d4c-1d1ddbd898d5.png)
Pressing the download button results into an error message oops...

**Comment by danielkesselberg** [comment]
Still broken on staging.

**Comment by danielkesselberg** [comment]
Fixed by #855 :tada: and works for me on staging.
