### ISSUE TITLE
EU-DSGVO: Delete Chat User Data

### ISSUE THREAD

**Issue by Gargamil** [geli-lms/geli#863]
# User Story

Tracking: #805 
### As a: 
User

### I want:
to ensure, that no personal data is stored in chats (ids). 

### so that:
No personal data (eg my id) is stored in chat.

## Acceptance criteria:
- [ ]

**Comment by lukas-schardt** [comment]
(blocked by #864)

**Comment by Gargamil** [comment]
no need to delete because ids after deleting the user are useless / anonymous
