### ISSUE TITLE
Course: Video-File switch view (as File-Type or Video)

### ISSUE THREAD

**Issue by Gargamil** [geli-lms/geli#912]
# User Story

### As a: 
Teacher

### I want:
display video in course either as File-Type or embedded Video

## Acceptance criteria:
- [ ]

**Comment by lukas-schardt** [comment]
@Gargamil Please specify.

**Comment by Gargamil** [comment]
Teacher can decide whether a video-file should be displayed as file (user can download) or embedded as video.
