### ISSUE TITLE
PDF export fails randomly

### ISSUE THREAD

**Issue by lukas-schardt** [geli-lms/geli#913]
# User Story

### As a: 
user of the GELI platform

### I want:
to export the course as PDF

## Acceptance criteria:
- [x] Display download button again
- [x] Rename temp file to be unique
- [x] Fix pdf generation and download
- [ ] Use `populate` (if possible) to remove `localLecture` and `localUnit`
- [ ] Invalidate cache when course / lecture / unit is edited

**Comment by danielkesselberg** [comment]
https://sentry.io/share/issue/230478b5826443daba938c0d0c7b0506/

**Comment by dboschm** [comment]
Can this be closed? PR #919 is already merged.

**Comment by danielkesselberg** [comment]
I added two other points to acceptance criteria today. I guess we should keep this ticket until we solved most issues with pdf export.
