### ISSUE TITLE
Teacher Course view: navigate between edit, preview and statistics

### ISSUE THREAD

**Issue by dboschm** [geli-lms/geli#924]
# User Story

### As a: 
Teacher 

### I want:
to access the statistics or the edit page from within the course view

### so that:
I no longer need to close the course to get the statistics of the same course 

## Acceptance criteria:
- [ ] Access to the stats from course edit (eg. like the "go to course" button)
- [ ] Open stats in a new tab / or add a "go back" button to the stats page
- [ ] Open edit from course preview

**Comment by Gargamil** [comment]
maybe it would be also helpful, if a teacher can go from course view directly to the edit of this?
