### ISSUE TITLE
Remove deprecation warnings

### ISSUE THREAD

**Issue by dboschm** [geli-lms/geli#934]
![grafik](https://user-images.githubusercontent.com/33879057/47735357-a9e90700-dc6c-11e8-983b-1e809976e95d.png)

- [ ] no more deprecation warnings in tests

**Comment by danielkesselberg** [comment]
Shit. I noticed this when I was upgrading sharp dependency and even read the upgrade guide.

**Comment by danielkesselberg** [comment]
https://github.com/lovell/sharp/blob/master/docs/changelog.md
