### ISSUE TITLE
Course image upload is broken

### ISSUE THREAD

**Issue by d89** [geli-lms/geli#974]
When I am trying to upload a picture as admin and teacher of a course, I receive this error:

![image](https://user-images.githubusercontent.com/423154/47956488-6ad8ef80-dfa5-11e8-90e3-d86714e71944.png)

**Comment by lukas-schardt** [comment]
Hi @d89, i am not really able to reproduce the error.  Locally and on staging. So a fix for this error could already be in the next release, which should be in a few days.
Nevertheless, could you attach the image you were trying to upload?

**Comment by danielkesselberg** [comment]
https://sentry.io/share/issue/51671e3f9fd246bd8baf86bce2d15d71/
https://sentry.io/share/issue/c3d9a70b65a34ff683cbc1a980f86a07/

**Comment by danielkesselberg** [comment]
I created a folder `courses` on prod. Upload works now. Folder was there on staging. I dont know if there is some kind of "migration" is missing.
